apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pe0bwuyde-go 
  janus-idp.io/tekton: pe0bwuyde-go
  backstage.io/kubernetes-id: pe0bwuyde-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pe0bwuyde-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  